#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Creates an animated gif of the NEB from aimsChain

Use Jmol to create images from a multi molecule xyz file.
Use Imagemagick to convert the generated .jpg's
and then use it again to convert the gifs for each iteration
into one long gif.

Usage: run this script from within the paths folder generated by aimsChain
Requirements: Jmol 11.7 and later, Imagemagick
"""

import os
import sys
import shutil as sh
import subprocess
import time

def makeScript():
  '''
  Creates the jmol script file
  '''

  with open('movie.jmol', 'w') as script:
    script.write('''frame 1 \n'''
                 '''num_frames = getProperty("modelInfo.modelCount")\n'''
                 '''for (var i = 1; i <= num_frames; i = i+1)\n'''
                 '''  var filename = "movie"+("00000"+i)[-4][0]+".jpg"\n'''
                 '''  write IMAGE 800 600 JPG @filename\n'''  
                 '''  frame next\n'''  
                 '''end for''')

def createImage(text, sizeX, sizeY, outputDir, outputName):
    """ Create square PNG image with white text and transparent background.
    The specified font must already exist on the local computer.

    source: http://danialgoodwin.com/blog/dev/dev-programmatically-generate-text-images-imagemagick-python/
    Modified to remove output dir, hardcoded Windows path, and generalized size
    """
    if not os.path.exists(outputDir):
        os.makedirs(outputDir)
    subprocess.call(["convert",
                     "-size", str(sizeX) + "x" + str(sizeY),
                     "-background", "#000000",
                     "-gravity", "center",
                     "-fill", "white",
                     "caption:" + text, 
                     outputName + ".jpg"])



#Walk through the directories and run Jmol and ImageMagick in each
#then move the resulting gif to the top level directory
for foldername, subfolders, filenames in os.walk('.'):
  for folder in subfolders:
    os.chdir(folder)
    makeScript()
    proc = subprocess.Popen(["jmol", "path.xyz -x -J movie.jmol"])
    time.sleep(4)
#    createImage(folder, 800, 600, ".", "movie")
#    time.sleep(2)
    subprocess.Popen("convert *.jpg " + folder +".gif", shell=True)
    time.sleep(4)
    sh.move(folder + '.gif', '..')

    os.remove('./movie.jmol')
    subprocess.Popen("rm *.jpg", shell=True)
    os.chdir('..') 

#Combine the resulting gifs into a mega gif and clean up
subprocess.Popen("convert *.gif allIterations.gif", shell=True)
subprocess.Popen("rm iteration*.gif", shell=True)
